@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImVtYWlsIjoidGVzdEB0ZXN0LmNvbSIsImlhdCI6MTY1MTQ3OTQ3MywiZXhwIjoxNjUxNTY1ODczfQ.IshaIIx1Jv8LvCKo0mZocCO1oVIm93O4bIEklDiTPFU

### Login
POST http://localhost:3000/login
Content-Type: application/json

{
  "email": "baw@test.com",
  "password": "baw"
}

### Register
POST http://localhost:3000/register
Content-Type: application/json

{
  "lastname": "test",
  "firstname": "test",
  "role": "admin",
  "email": "baw@test.com",
  "password": "baw"
}

### GET all users
GET http://localhost:3000/users
// use token variable
Authorization: Bearer {{token}}

### Create a user with a POST request using lastname, firstname, email, password
POST http://localhost:3000/users
Content-Type: application/json

{
  "lastname": "Doe",
  "firstname": "John",
  "email": "test@test.com",
  "password": "test"
}

### GET a user
GET http://localhost:3000/users/1


### Update a user with a PUT request using lastname, firstname, email, password
PUT http://localhost:3000/users/7
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTEsImVtYWlsIjoiYmF3QHRlc3QuY29tIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNjUwOTg4MzIyLCJleHAiOjE2NTEwNzQ3MjJ9.MqIphWzkGfczA9zIUlEcppZM8RYtYMH5F3asgiazBo4
Content-Type: application/json

{
  "lastname": "Doe",
  "firstname": "Jane"
}

### Delete a user with a DELETE request
DELETE http://localhost:3000/users/1

# ORDERS

### Create a order with a POST request using shippingAddress
POST http://localhost:3000/orders
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "cart": [
    { "productId": 1, "quantity": 10 },
    { "productId": 2, "quantity": 20}
  ],
  "shippingAddress": "5 rue Général, 75015 Paris"
}

### Create a order with a POST request using shippingAddress
GET http://localhost:3000/test/pdf

### Create a bill with a POST request
POST http://localhost:3000/test/bill
Authorization: Bearer {{token}}
Content-Type: application/json  

{
  "orderId" : 6
}

###


DELETE http://localhost:3000/test/bill/1
Authorization: Bearer {{token}}
Content-Type: application/json  

{
  "orderId" :1
}
### Create payment intent
POST http://localhost:3000/payment
Content-Type: application/json

{
  "id": 12
}
