@tokenUser=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJiYXdAdGVzdC5jb20iLCJyb2xlIjoidXNlciIsImlhdCI6MTY1MTQ5MzQwMSwiZXhwIjoxNjUxNTc5ODAxfQ.HMi_KUOp16DmThBUXvmIWpcNlE2O_aI4fvGBz74-Hrg
@tokenAdmin=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiZW1haWwiOiJhZG1pbkB0ZXN0LmNvbSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTY1MTQ5MzQzOSwiZXhwIjoxNjUxNTc5ODM5fQ.ilBsEZpaSXjwmgJFgVzW3jcMgsxGb63--A2JriTyh9o


### Get stocks quantity
GET http://localhost:3000/products/4/stock
Authorization: Bearer {{tokenUser}}

### Get stocks events
GET http://localhost:3000/products/4/stock_events
Authorization: Bearer {{tokenUser}}

### POST stocks events
POST http://localhost:3000/products/4/stock_events
Authorization: Bearer {{tokenUser}}
Content-Type: application/json

{
  "typeEvent": "RESERVATION",
  "quantity": 10
}

### DELETE stocks events
DELETE http://localhost:3000/products/4/stock_events/4
Authorization: Bearer {{tokenUser}}