@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwiZW1haWwiOiJiaUBiaS5jb20iLCJpYXQiOjE2NTI3MTc0MTEsImV4cCI6MTY1MjgwMzgxMX0.PAe8MqMFIdZs5M4KSjKVaIXYLKVvJwCvybzMfZWihsk

### Login
POST http://localhost:3000/login
Content-Type: application/json

{
  "email": "bi@bi.com",
  "password": "bi"
}

### Register
POST http://localhost:3000/register
Content-Type: application/json

{
  "lastname": "gui",
  "firstname": "gui",
  "email": "gui@gui.com",
  "password": "gui"
}

### Verify Bearer token
POST http://localhost:3000/verify-token
Authorization: Bearer {{token}}

### GET all users
GET http://localhost:3000/users
Authorization: Bearer {{token}}

### Create a user with a POST request using lastname, firstname, email, password
POST http://localhost:3000/users
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "lastname": "Doe",
  "firstname": "John",
  "email": "baw@baw.com",
  "password": "baw"
}

### GET a user
GET http://localhost:3000/users/1
Authorization: Bearer {{token}}

### Update a user with a PUT request using lastname, firstname, email, password
PUT http://localhost:3000/users/1
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "lastname": "Rick",
  "firstname": "Rack"
}

### Delete a user with a DELETE request
DELETE http://localhost:3000/users/2
Authorization: Bearer {{token}}
